# Demo code from a public repo, so published public. The registry defaults to private.
visibility: public

components:
  PongModule/Pong:
    metadata:
      route: /pong
      displayName: Pong Micro-Frontend
      displayGroup: main
      order: 20
      icon: ViewList

  PongModule/CoolComponent:
    metadata:
      route: /cool
      displayName: Cool Shared Component
      displayGroup: main
      order: 30
      icon: ViewList
